import type { LanguageCode } from "../i18n";

const en = {
  heading: "Property records",
  scope: "These records belong to the current property-owner workspace.",
  ownerTitle: "Property Owner workspace",
  ownerNote: "Switch to the property owner workspace to open its portfolio.",
  overview: "Back to overview",
  all: "All properties",
  withRent: "With rent records",
  withoutRent: "Without rent records",
  search: "Search portfolio",
  searchPlaceholder: "Search property name or address",
  sort: "Sort portfolio",
  issuesFirst: "Open repairs first",
  rentHigh: "Listed price: high to low",
  name: "Property name",
  reset: "Reset filters",
  rental: "Rental listing",
  sale: "Sale listing",
  rentRecords: "Rent records",
  openRepairs: "Open repairs",
  monthlyRent: "Listed monthly rent",
  askingPrice: "Asking price",
  next: "Next action",
  reviewRepairs: "Review repairs",
  reviewRent: "Review rent records",
  open: "Open property",
  noMatches: "No properties match these filters.",
  noMatchesHint: "Try another name or reset the filters.",
  result: "Properties shown",
  period: "Rent record for this month",
};
type Copy = Record<keyof typeof en, string>;
const dictionaries: Record<LanguageCode, Copy> = {
  en,
  pt: {
    heading: "Registos de imóveis",
    scope: "Estes registos pertencem à área do proprietário atual.",
    ownerTitle: "Área do proprietário",
    ownerNote: "Mude para a área do proprietário para abrir os seus imóveis.",
    overview: "Voltar à visão geral",
    all: "Todos os imóveis",
    withRent: "Com registos de renda",
    withoutRent: "Sem registos de renda",
    search: "Pesquisar imóveis da carteira",
    searchPlaceholder: "Pesquisar nome ou morada do imóvel",
    sort: "Ordenar imóveis",
    issuesFirst: "Reparações em aberto primeiro",
    rentHigh: "Preço anunciado: do maior ao menor",
    name: "Nome do imóvel",
    reset: "Limpar filtros",
    rental: "Anúncio de arrendamento",
    sale: "Anúncio de venda",
    rentRecords: "Registos de renda",
    openRepairs: "Reparações em aberto",
    monthlyRent: "Renda mensal anunciada",
    askingPrice: "Preço pedido",
    next: "Próxima ação",
    reviewRepairs: "Ver reparações",
    reviewRent: "Ver registos de renda",
    open: "Abrir imóvel",
    noMatches: "Nenhum imóvel corresponde a estes filtros.",
    noMatchesHint: "Experimente outro nome ou limpe os filtros.",
    result: "Imóveis apresentados",
    period: "Registo de renda deste mês",
  },
  es: {
    heading: "Registros de inmuebles",
    scope: "Estos registros pertenecen al espacio del propietario actual.",
    ownerTitle: "Espacio del propietario",
    ownerNote: "Cambie al espacio del propietario para abrir su cartera.",
    overview: "Volver al resumen",
    all: "Todos los inmuebles",
    withRent: "Con registros de alquiler",
    withoutRent: "Sin registros de alquiler",
    search: "Buscar inmuebles de la cartera",
    searchPlaceholder: "Buscar por nombre o dirección",
    sort: "Ordenar inmuebles",
    issuesFirst: "Reparaciones abiertas primero",
    rentHigh: "Precio anunciado: de mayor a menor",
    name: "Nombre del inmueble",
    reset: "Borrar filtros",
    rental: "Anuncio de alquiler",
    sale: "Anuncio de venta",
    rentRecords: "Registros de alquiler",
    openRepairs: "Reparaciones abiertas",
    monthlyRent: "Alquiler mensual anunciado",
    askingPrice: "Precio solicitado",
    next: "Próxima acción",
    reviewRepairs: "Ver reparaciones",
    reviewRent: "Ver registros de alquiler",
    open: "Abrir inmueble",
    noMatches: "Ningún inmueble coincide con estos filtros.",
    noMatchesHint: "Pruebe otro nombre o borre los filtros.",
    result: "Inmuebles mostrados",
    period: "Registro de alquiler de este mes",
  },
  fr: {
    heading: "Dossiers des biens",
    scope: "Ces dossiers appartiennent à l’espace du propriétaire actuel.",
    ownerTitle: "Espace propriétaire",
    ownerNote: "Passez à l’espace propriétaire pour ouvrir son portefeuille.",
    overview: "Retour à la vue d’ensemble",
    all: "Tous les biens",
    withRent: "Avec des relevés de loyer",
    withoutRent: "Sans relevé de loyer",
    search: "Rechercher dans les biens",
    searchPlaceholder: "Rechercher un nom ou une adresse",
    sort: "Trier les biens",
    issuesFirst: "Réparations ouvertes en premier",
    rentHigh: "Prix annoncé : décroissant",
    name: "Nom du bien",
    reset: "Réinitialiser les filtres",
    rental: "Annonce de location",
    sale: "Annonce de vente",
    rentRecords: "Relevés de loyer",
    openRepairs: "Réparations ouvertes",
    monthlyRent: "Loyer mensuel annoncé",
    askingPrice: "Prix demandé",
    next: "Prochaine action",
    reviewRepairs: "Voir les réparations",
    reviewRent: "Voir les relevés de loyer",
    open: "Ouvrir le bien",
    noMatches: "Aucun bien ne correspond à ces filtres.",
    noMatchesHint: "Essayez un autre nom ou réinitialisez les filtres.",
    result: "Biens affichés",
    period: "Relevé de loyer du mois",
  },
  ar: {
    heading: "سجلات العقارات",
    scope: "تخص هذه السجلات مساحة عمل مالك العقار الحالي.",
    ownerTitle: "مساحة مالك العقار",
    ownerNote: "انتقل إلى مساحة مالك العقار لفتح عقاراته.",
    overview: "العودة إلى النظرة العامة",
    all: "جميع العقارات",
    withRent: "مع سجلات إيجار",
    withoutRent: "دون سجلات إيجار",
    search: "البحث في العقارات",
    searchPlaceholder: "ابحث بالاسم أو العنوان",
    sort: "ترتيب العقارات",
    issuesFirst: "الإصلاحات المفتوحة أولاً",
    rentHigh: "السعر المعلن: من الأعلى إلى الأقل",
    name: "اسم العقار",
    reset: "إعادة ضبط عوامل التصفية",
    rental: "إعلان للإيجار",
    sale: "إعلان للبيع",
    rentRecords: "سجلات الإيجار",
    openRepairs: "الإصلاحات المفتوحة",
    monthlyRent: "الإيجار الشهري المعلن",
    askingPrice: "السعر المطلوب",
    next: "الإجراء التالي",
    reviewRepairs: "عرض الإصلاحات",
    reviewRent: "عرض سجلات الإيجار",
    open: "فتح العقار",
    noMatches: "لا توجد عقارات تطابق عوامل التصفية.",
    noMatchesHint: "جرّب اسماً آخر أو أعد ضبط عوامل التصفية.",
    result: "العقارات المعروضة",
    period: "سجل إيجار هذا الشهر",
  },
  zh: {
    heading: "房产记录",
    scope: "这些记录属于当前业主工作区。",
    ownerTitle: "业主工作区",
    ownerNote: "切换到业主工作区以查看房产。",
    overview: "返回概览",
    all: "所有房产",
    withRent: "有租金记录",
    withoutRent: "无租金记录",
    search: "搜索房产",
    searchPlaceholder: "搜索房产名称或地址",
    sort: "房产排序",
    issuesFirst: "未完成维修优先",
    rentHigh: "挂牌价格：从高到低",
    name: "房产名称",
    reset: "重置筛选",
    rental: "出租房源",
    sale: "出售房源",
    rentRecords: "租金记录",
    openRepairs: "未完成维修",
    monthlyRent: "公布的月租金",
    askingPrice: "报价",
    next: "下一步",
    reviewRepairs: "查看维修",
    reviewRent: "查看租金记录",
    open: "打开房产",
    noMatches: "没有符合筛选条件的房产。",
    noMatchesHint: "请尝试其他名称或重置筛选。",
    result: "显示房产数",
    period: "本月租金记录",
  },
};

export function propertyPortfolioCopy(language: string): Copy {
  const key = language.split("-")[0] as LanguageCode;
  const copy = dictionaries[key] ?? dictionaries.pt;
  if (key !== "ar" && key !== "zh") return copy;
  return Object.fromEntries(
    Object.entries(copy).map(([name, value]) => [
      name,
      `${value} (${en[name as keyof Copy]})`,
    ]),
  ) as Copy;
}
