import "./navigation-check";
import "./search-check";
import "./messages-check";
import "./application-state-check";
import "./notification-check";
import "./bookings-check";
import "./discover-state-check";
import "./preferences-check";
import "./saved-search-state-check";
import "./workspace-saved-state-check";
import "./property-request-check";
import "./maintenance-state-check";
import "./document-state-check";
import "./rent-record-state-check";
import "./property-operations-summary-check";
import "./property-insights-check";
import "./property-listing-state-check";
import "./service-request-state-check";
import "./operations-localization-check";

console.log("Kasa UI state checks passed.");
