import type {
  Application,
  MaintenanceRequest,
  Property,
  SpaceBooking,
  SpaceVenue,
} from "./types";

export const properties: Property[] = [
  {
    id: 1,
    title: "Sunlit Eixample home",
    address: "Carrer de Mallorca, 214",
    city: "Barcelona",
    price: 1850,
    beds: 2,
    baths: 2,
    sqm: 92,
    image:
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85",
    tag: "Great match",
    available: "Available now",
    furnished: true,
    landlord: "Olivia Martín",
    match: 96,
    listingType: "Rent",
    propertyType: "Apartment",
    verified: true,
    neighbourhood: "Eixample",
    lat: 41.391,
    lng: 2.164,
    deposit: 1850,
    description:
      "A calm, light-filled apartment with restored details, generous storage and a balcony overlooking a quiet Eixample courtyard.",
    amenities: [
      "Balcony",
      "Lift",
      "Air conditioning",
      "Furnished",
      "High-speed internet",
      "Accessible entry",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=85",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85",
    ],
  },
  {
    id: 2,
    title: "Quiet Gràcia loft",
    address: "Carrer de Verdi, 88",
    city: "Barcelona",
    price: 1420,
    beds: 1,
    baths: 1,
    sqm: 64,
    image:
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
    tag: "New",
    available: "Available 1 Sep",
    furnished: true,
    landlord: "Nuno Silva",
    match: 91,
    listingType: "Rent",
    propertyType: "Loft",
    verified: true,
    neighbourhood: "Gràcia",
    lat: 41.404,
    lng: 2.157,
    deposit: 1420,
    description:
      "A characterful, furnished loft close to Plaça de la Vila with a flexible open plan and a peaceful sleeping mezzanine.",
    amenities: [
      "Furnished",
      "Air conditioning",
      "Dishwasher",
      "Pet friendly",
      "High-speed internet",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85",
      "https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=900&q=85",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=85",
    ],
  },
  {
    id: 3,
    title: "Poblenou terrace studio",
    address: "Carrer de Pujades, 121",
    city: "Barcelona",
    price: 1280,
    beds: 1,
    baths: 1,
    sqm: 51,
    image:
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85",
    available: "Available 15 Sep",
    furnished: false,
    landlord: "Sofia Costa",
    match: 87,
    listingType: "Rent",
    propertyType: "Studio",
    verified: false,
    neighbourhood: "Poblenou",
    lat: 41.399,
    lng: 2.194,
    deposit: 1280,
    description:
      "Compact studio with a private terrace, practical storage and quick access to the beach and innovation district.",
    amenities: [
      "Private terrace",
      "Lift",
      "Bike storage",
      "High-speed internet",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=900&q=85",
      "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=900&q=85",
    ],
  },
  {
    id: 4,
    title: "Sant Antoni family flat",
    address: "Carrer del Parlament, 42",
    city: "Barcelona",
    price: 2100,
    beds: 3,
    baths: 2,
    sqm: 118,
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
    tag: "Promoted",
    available: "Available 1 Oct",
    furnished: false,
    landlord: "Mateo Ruiz",
    match: 82,
    listingType: "Rent",
    propertyType: "Apartment",
    verified: true,
    neighbourhood: "Sant Antoni",
    lat: 41.378,
    lng: 2.161,
    deposit: 2100,
    description:
      "Spacious family apartment with three bedrooms, a large kitchen and bright corner living room near the market.",
    amenities: [
      "Lift",
      "Balcony",
      "Family friendly",
      "Storage",
      "Parking nearby",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=900&q=85",
    ],
  },
  {
    id: 5,
    title: "Gràcia courtyard house",
    address: "Carrer de l’Encarnació, 63",
    city: "Barcelona",
    price: 595000,
    beds: 3,
    baths: 2,
    sqm: 136,
    image:
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=85",
    tag: "New",
    available: "For sale",
    furnished: false,
    landlord: "Clara Vidal",
    match: 90,
    listingType: "Buy",
    propertyType: "House",
    verified: true,
    neighbourhood: "Gràcia",
    lat: 41.407,
    lng: 2.159,
    deposit: 0,
    description:
      "Illustrative sale listing for a quiet courtyard house with flexible living space and a private terrace.",
    amenities: [
      "Private terrace",
      "Storage",
      "Air conditioning",
      "Natural light",
      "Quiet street",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1400&q=85",
      "https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=900&q=85",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85",
    ],
  },
  {
    id: 6,
    title: "Poblenou modern duplex",
    address: "Carrer de Llull, 189",
    city: "Barcelona",
    price: 725000,
    beds: 3,
    baths: 3,
    sqm: 154,
    image:
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=85",
    available: "For sale",
    furnished: true,
    landlord: "Marc Ferrer",
    match: 85,
    listingType: "Buy",
    propertyType: "Apartment",
    verified: false,
    neighbourhood: "Poblenou",
    lat: 41.402,
    lng: 2.191,
    deposit: 0,
    description:
      "Illustrative sale listing for a bright duplex with a large living area and outdoor space close to the coast.",
    amenities: ["Terrace", "Lift", "Parking", "Air conditioning", "Storage"],
    gallery: [
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1400&q=85",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85",
    ],
  },
];

export const applications: Application[] = [
  {
    id: 1,
    applicant: "Amira Hassan",
    property: "Sunlit Eixample home",
    submitted: "Today, 09:42",
    status: "Review",
    score: 92,
    avatar: "AH",
  },
  {
    id: 2,
    applicant: "Leo Bernard",
    property: "Quiet Gràcia loft",
    submitted: "Yesterday",
    status: "Documents",
    score: 88,
    avatar: "LB",
  },
  {
    id: 3,
    applicant: "Inês Duarte",
    property: "Sunlit Eixample home",
    submitted: "18 Aug",
    status: "Approved",
    score: 95,
    avatar: "ID",
  },
  {
    id: 4,
    applicant: "Maya Chen",
    property: "Poblenou terrace studio",
    submitted: "16 Aug",
    status: "Draft",
    score: 81,
    avatar: "MC",
  },
];

export const maintenance: MaintenanceRequest[] = [
  {
    id: 1,
    title: "Kitchen tap leaking",
    property: "Sunlit Eixample home",
    tenant: "Inês Duarte",
    status: "New",
    priority: "Medium",
    date: "Today",
  },
  {
    id: 2,
    title: "Air conditioning service",
    property: "Quiet Gràcia loft",
    tenant: "Leo Bernard",
    status: "Scheduled",
    priority: "Low",
    date: "22 Aug",
    provider: "Clima BCN",
  },
  {
    id: 3,
    title: "Power outlet not working",
    property: "Poblenou terrace studio",
    tenant: "Maya Chen",
    status: "In progress",
    priority: "Urgent",
    date: "19 Aug",
    provider: "Volt & Co.",
  },
  {
    id: 4,
    title: "Bedroom blind repair",
    property: "Sunlit Eixample home",
    tenant: "Inês Duarte",
    status: "Resolved",
    priority: "Low",
    date: "12 Aug",
    provider: "Fixly",
  },
];

export const providers = [
  {
    name: "Volt & Co.",
    type: "Electrical",
    rating: 4.9,
    jobs: 128,
    response: "~1 hour",
    initials: "V",
    tone: "sun",
    price: "From €65",
    priceValue: 65,
    mode: "Fixed-price visits",
    pricing: "Fixed price",
    providerKind: "Company",
    availability: "Today",
  },
  {
    name: "Clima BCN",
    type: "AC & climate",
    rating: 4.8,
    jobs: 96,
    response: "~2 hours",
    initials: "C",
    tone: "mint",
    price: "From €79",
    priceValue: 79,
    mode: "Fixed price + quotes",
    pricing: "Quote available",
    providerKind: "Company",
    availability: "This week",
  },
  {
    name: "Fixly",
    type: "Handyman",
    rating: 4.9,
    jobs: 213,
    response: "~45 min",
    initials: "F",
    tone: "lilac",
    price: "From €45",
    priceValue: 45,
    mode: "Hourly or quote",
    pricing: "Quote available",
    providerKind: "Independent",
    availability: "Today",
  },
  {
    name: "Aigua Pro",
    type: "Plumbing",
    rating: 4.7,
    jobs: 174,
    response: "~1 hour",
    initials: "A",
    tone: "blue",
    price: "From €59",
    priceValue: 59,
    mode: "Fixed-price visits",
    pricing: "Fixed price",
    providerKind: "Company",
    availability: "Tomorrow",
  },
  {
    name: "Casa Clara",
    type: "Cleaning",
    rating: 4.8,
    jobs: 241,
    response: "~40 min",
    initials: "CC",
    tone: "mint",
    price: "From €48",
    priceValue: 48,
    mode: "Fixed price + recurring",
    pricing: "Fixed price",
    providerKind: "Company",
    availability: "Today",
  },
];

export const conversations = [
  {
    name: "Inês Duarte",
    property: "Sunlit Eixample home",
    preview: "I’ve uploaded the transfer receipt.",
    time: "09:42",
    unread: 2,
    initials: "ID",
  },
  {
    name: "Leo Bernard",
    property: "Quiet Gràcia loft",
    preview: "Thursday afternoon works for me.",
    time: "Yesterday",
    unread: 0,
    initials: "LB",
  },
  {
    name: "Clima BCN",
    property: "Maintenance · #1028",
    preview: "Your visit is confirmed for 22 Aug.",
    time: "Yesterday",
    unread: 0,
    initials: "CB",
  },
];

const padelImage =
  "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=85";
const footballImage =
  "https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1200&q=85";
const eventImage =
  "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=85";

export const spaceVenues: SpaceVenue[] = [
  {
    id: 1,
    name: "Poblenou MultiSport Club",
    category: "Sports",
    address: "Carrer de la Marina, 88",
    neighbourhood: "Poblenou",
    lat: 41.4007,
    lng: 2.1915,
    distance: "0.8 km",
    priceFrom: 28,
    priceUnit: "/ 90 min",
    rating: 4.8,
    reviews: 214,
    image: padelImage,
    gallery: [padelImage, footballImage, padelImage],
    availableToday: true,
    verified: true,
    bookingMode: "Instant Book",
    description:
      "A multi-sport neighbourhood facility with bookable padel courts and football pitches.",
    amenities: [
      "Changing rooms",
      "Parking nearby",
      "Court lighting",
      "Equipment rental",
      "Showers",
      "Accessible entry",
    ],
    openingHours: "06:00–23:00",
    spaces: [
      {
        id: 11,
        name: "Court 1",
        activity: "Padel",
        price: 28,
        peakPrice: 36,
        image: padelImage,
        capacity: 4,
        slots: [
          { time: "08:00–09:30", status: "Available", price: 28 },
          { time: "09:30–11:00", status: "Booked", price: 28 },
          { time: "11:00–12:30", status: "Available", price: 28 },
          { time: "17:00–18:30", status: "Peak", price: 36 },
          { time: "18:30–20:00", status: "Peak", price: 36 },
          { time: "20:00–21:30", status: "Available", price: 32 },
        ],
      },
      {
        id: 12,
        name: "Court 2",
        activity: "Padel",
        price: 28,
        peakPrice: 36,
        image: padelImage,
        capacity: 4,
        slots: [
          { time: "08:00–09:30", status: "Booked", price: 28 },
          { time: "09:30–11:00", status: "Available", price: 28 },
          { time: "11:00–12:30", status: "Available", price: 28 },
          { time: "17:00–18:30", status: "Peak", price: 36 },
          { time: "18:30–20:00", status: "Booked", price: 36 },
          { time: "20:00–21:30", status: "Available", price: 32 },
        ],
      },
      {
        id: 13,
        name: "Pitch A",
        activity: "Football 5-a-side",
        price: 48,
        peakPrice: 62,
        image: footballImage,
        capacity: 12,
        slots: [
          { time: "08:00–09:30", status: "Available", price: 48 },
          { time: "09:30–11:00", status: "Available", price: 48 },
          { time: "11:00–12:30", status: "Booked", price: 48 },
          { time: "17:00–18:30", status: "Peak", price: 62 },
          { time: "18:30–20:00", status: "Peak", price: 62 },
          { time: "20:00–21:30", status: "Booked", price: 62 },
        ],
      },
      {
        id: 14,
        name: "Pitch B",
        activity: "Football 7-a-side",
        price: 68,
        peakPrice: 84,
        image: footballImage,
        capacity: 18,
        slots: [
          { time: "08:00–09:30", status: "Available", price: 68 },
          { time: "09:30–11:00", status: "Booked", price: 68 },
          { time: "11:00–12:30", status: "Available", price: 68 },
          { time: "17:00–18:30", status: "Peak", price: 84 },
          { time: "18:30–20:00", status: "Peak", price: 84 },
          { time: "20:00–21:30", status: "Available", price: 78 },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Marina Padel Club",
    category: "Sports",
    address: "Passeig Marítim, 41",
    neighbourhood: "Barceloneta",
    lat: 41.3778,
    lng: 2.192,
    distance: "1.4 km",
    priceFrom: 24,
    priceUnit: "/ 90 min",
    rating: 4.7,
    reviews: 168,
    image: padelImage,
    gallery: [padelImage, padelImage, padelImage],
    availableToday: true,
    verified: true,
    bookingMode: "Instant Book",
    description:
      "Four outdoor padel courts close to the waterfront with equipment hire and evening lighting.",
    amenities: [
      "Equipment rental",
      "Court lighting",
      "Lockers",
      "Water station",
    ],
    openingHours: "07:00–22:30",
    spaces: [
      {
        id: 21,
        name: "Sea Court",
        activity: "Padel",
        price: 24,
        peakPrice: 32,
        image: padelImage,
        capacity: 4,
        slots: [
          { time: "08:00–09:30", status: "Available", price: 24 },
          { time: "09:30–11:00", status: "Booked", price: 24 },
          { time: "11:00–12:30", status: "Available", price: 24 },
          { time: "18:30–20:00", status: "Peak", price: 32 },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Montjuïc Football Hub",
    category: "Sports",
    address: "Avinguda de l’Estadi, 12",
    neighbourhood: "Montjuïc",
    lat: 41.367,
    lng: 2.148,
    distance: "2.9 km",
    priceFrom: 52,
    priceUnit: "/ 90 min",
    rating: 4.6,
    reviews: 103,
    image: footballImage,
    gallery: [footballImage, footballImage, footballImage],
    availableToday: false,
    verified: true,
    bookingMode: "Instant Book",
    description:
      "Well-lit football pitches for teams, training groups and recurring weekly sessions.",
    amenities: ["Changing rooms", "Floodlights", "Parking", "Ball rental"],
    openingHours: "08:00–23:00",
    spaces: [
      {
        id: 31,
        name: "Pitch 1",
        activity: "Football 7-a-side",
        price: 52,
        peakPrice: 68,
        image: footballImage,
        capacity: 18,
        slots: [
          { time: "08:00–09:30", status: "Booked", price: 52 },
          { time: "09:30–11:00", status: "Available", price: 52 },
          { time: "17:00–18:30", status: "Peak", price: 68 },
          { time: "20:00–21:30", status: "Available", price: 64 },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "The Garden Hall",
    category: "Events",
    address: "Carrer de la Llacuna, 127",
    neighbourhood: "Poblenou",
    lat: 41.404,
    lng: 2.195,
    distance: "1.9 km",
    priceFrom: 680,
    priceUnit: "/ event",
    rating: 4.8,
    reviews: 86,
    image: eventImage,
    gallery: [
      eventImage,
      "https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=85",
    ],
    availableToday: false,
    verified: true,
    bookingMode: "Request to Book",
    description:
      "A bright flexible hall for private celebrations, workshops and community events, managed directly by the venue operator.",
    amenities: [
      "150 guests seated",
      "Tables & chairs",
      "Kitchen",
      "Catering allowed",
      "Parking nearby",
      "Sound system",
      "Decoration with approval",
    ],
    capacity: 180,
    openingHours: "09:00–23:00",
    cleaningFee: 120,
    deposit: 300,
    spaces: [
      {
        id: 41,
        name: "Main Hall",
        activity: "Events",
        price: 680,
        peakPrice: 820,
        image: eventImage,
        capacity: 180,
        slots: [
          { time: "10:00–14:00", status: "Available", price: 680 },
          { time: "15:00–19:00", status: "Booked", price: 680 },
          { time: "18:00–23:00", status: "Peak", price: 820 },
        ],
      },
    ],
  },
];

export const spaceBookings: SpaceBooking[] = [
  {
    id: "KS-7M52X",
    venue: "Poblenou MultiSport Club",
    space: "Court 1 — Padel",
    date: "24 Aug",
    time: "17:00–18:30",
    status: "Upcoming",
    price: 36,
    image: padelImage,
    code: "KSA7-M52X",
  },
  {
    id: "KS-2P18A",
    venue: "Marina Padel Club",
    space: "Sea Court — Padel",
    date: "16 Aug",
    time: "09:30–11:00",
    status: "Completed",
    price: 24,
    image: padelImage,
    code: "KSA2-P18A",
  },
  {
    id: "KS-9H31C",
    venue: "The Garden Hall",
    space: "Main Hall",
    date: "12 Sep",
    time: "18:00–23:00",
    status: "Requested",
    price: 820,
    image: eventImage,
    code: "KSA9-H31C",
  },
];
